apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: {{ include "mediatracker.fullname" . }}
  name: {{ include "mediatracker.fullname" . }}-assets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: {{ include "mediatracker.fullname" . }}
  name: {{ include "mediatracker.fullname" . }}-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
