version: 2.1

jobs:
  node-v16:
    docker:
      - image: cimg/node:18.14.1
    steps:
      - test
      
commands:
  store-coverage-data:
    steps:
      - store_artifacts:
          path: server/coverage
  test:
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependancies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - $HOME/.npm
      - run:
          name: test
          command: |
            npm run test
      - store_test_results:
          path: server/junit.xml

workflows:
  version: 2
  test:
    jobs:
      - node-v16