import axios from 'axios';
import { Audible } from 'src/metadata/provider/audible';
import { clearDatabase, runMigrations } from '__tests__/__utils__/utils';

jest.mock('axios');

const mockedAxios = axios as jest.Mocked<typeof axios>;
const audible = new Audible();

describe('openlibrary', () => {
  beforeAll(runMigrations);
  afterAll(clearDatabase);

  test('search', async () => {
    mockedAxios.get.mockResolvedValue({ data: searchResponse, status: 200 });

    const res = await audible.search('Harry Potter');

    expect(res).toStrictEqual(searchResult);
  });

  test('details', async () => {
    mockedAxios.get.mockResolvedValue({ data: detailsResponse, status: 200 });

    const res = await audible.details({
      openlibraryId: 'B017V4IM1G',
    });

    expect(res).toStrictEqual(detailsResult);
  });
});

const searchResult = [
  {
    needsDetails: false,
    mediaType: 'audiobook',
    source: 'audible',
    title: "Harry Potter and the Sorcerer's Stone, Book 1",
    audibleId: 'B017V4IM1G',
    authors: ['J.K. Rowling'],
    narrators: ['Jim Dale'],
    poster: 'https://m.media-amazon.com/images/I/91tDBrO2u9L._SL2400_.jpg',
    language: 'english',
    releaseDate: '2015-11-20',
    runtime: 498,
    overview:
      '<p>Harry Potter is a wizard - and not only a wizard, he’s an incredibly famous wizard. Rubeus Hagrid spirits him away from his less-than-fortunate life to Hogwarts School of Witchcraft and Wizardry, setting into motion an incredible adventure....</p>',
  },
  {
    needsDetails: false,
    mediaType: 'audiobook',
    source: 'audible',
    title: 'Harry Potter and the Goblet of Fire, Book 4',
    audibleId: 'B017V4NUPO',
    authors: ['J.K. Rowling'],
    narrators: ['Jim Dale'],
    poster: 'https://m.media-amazon.com/images/I/91wE69EbTKL._SL2400_.jpg',
    language: 'english',
    releaseDate: '2015-11-20',
    runtime: 1237,
    overview:
      "The Triwizard Tournament is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter - but that doesn't stop Harry dreaming that he will win the competition....",
  },
  {
    needsDetails: false,
    mediaType: 'audiobook',
    source: 'audible',
    title: 'Harry Potter and the Prisoner of Azkaban, Book 3',
    audibleId: 'B017V4JA2Q',
    authors: ['J.K. Rowling'],
    narrators: ['Jim Dale'],
    poster: 'https://m.media-amazon.com/images/I/91wkoe9lV4L._SL2400_.jpg',
    language: 'english',
    releaseDate: '2015-11-20',
    runtime: 709,
    overview:
      "<p>When the Knight Bus crashes through the darkness and screeches to a halt in front of him, it's the start of another far-from-ordinary year at Hogwarts for Harry Potter....</p>",
  },
  {
    needsDetails: false,
    mediaType: 'audiobook',
    source: 'audible',
    title: 'Harry Potter and the Order of the Phoenix, Book 5',
    audibleId: 'B017V4NMX4',
    authors: ['J.K. Rowling'],
    narrators: ['Jim Dale'],
    poster: 'https://m.media-amazon.com/images/I/91lexie8rNL._SL2400_.jpg',
    language: 'english',
    releaseDate: '2015-11-20',
    runtime: 1589,
    overview:
      "Dark times have come to Hogwarts. After the Dementors' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him....",
  },
  {
    needsDetails: false,
    mediaType: 'audiobook',
    source: 'audible',
    title: 'Harry Potter and the Chamber of Secrets, Book 2',
    audibleId: 'B017V4IWVG',
    authors: ['J.K. Rowling'],
    narrators: ['Jim Dale'],
    poster: 'https://m.media-amazon.com/images/I/91esnMgE8dL._SL2400_.jpg',
    language: 'english',
    releaseDate: '2015-11-20',
    runtime: 543,
    overview:
      'Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start....',
  },
];

const detailsResult = {
  needsDetails: false,
  mediaType: 'audiobook',
  source: 'audible',
  title: "Harry Potter and the Sorcerer's Stone, Book 1",
  audibleId: 'B017V4IM1G',
  authors: ['J.K. Rowling'],
  narrators: ['Jim Dale'],
  poster: 'https://m.media-amazon.com/images/I/91tDBrO2u9L._SL2400_.jpg',
  language: 'english',
  releaseDate: '2015-11-20',
  runtime: 498,
  overview:
    '<p>Harry Potter is a wizard - and not only a wizard, he’s an incredibly famous wizard. Rubeus Hagrid spirits him away from his less-than-fortunate life to Hogwarts School of Witchcraft and Wizardry, setting into motion an incredible adventure....</p>',
};

const detailsResponse = {
  product: {
    asin: 'B017V4IM1G',
    authors: [{ asin: 'B000AP9A6K', name: 'J.K. Rowling' }],
    available_codecs: [
      {
        enhanced_codec: 'LC_32_22050_stereo',
        format: 'Enhanced',
        is_kindle_enhanced: true,
        name: 'aax_22_32',
      },
      {
        enhanced_codec: 'LC_64_22050_stereo',
        format: 'Enhanced',
        is_kindle_enhanced: true,
        name: 'aax_22_64',
      },
      {
        enhanced_codec: 'format4',
        format: 'Format4',
        is_kindle_enhanced: false,
        name: 'format4',
      },
      {
        enhanced_codec: 'mp42232',
        format: 'Enhanced',
        is_kindle_enhanced: true,
        name: 'mp4_22_32',
      },
      {
        enhanced_codec: 'mp42264',
        format: 'Enhanced',
        is_kindle_enhanced: true,
        name: 'mp4_22_64',
      },
      {
        enhanced_codec: 'aax',
        format: 'Enhanced',
        is_kindle_enhanced: false,
        name: 'aax',
      },
    ],
    content_delivery_type: 'SinglePartBook',
    content_type: 'Product',
    format_type: 'unabridged',
    has_children: false,
    is_adult_product: false,
    is_listenable: true,
    is_purchasability_suppressed: false,
    issue_date: '2015-11-20',
    language: 'english',
    merchandising_summary:
      '<p>Harry Potter is a wizard - and not only a wizard, he’s an incredibly famous wizard. Rubeus Hagrid spirits him away from his less-than-fortunate life to Hogwarts School of Witchcraft and Wizardry, setting into motion an incredible adventure....</p>',
    narrators: [{ name: 'Jim Dale' }],
    product_images: {
      '500': 'https://m.media-amazon.com/images/I/51U4p-ir2BL._SL500_.jpg',
      '1000': 'https://m.media-amazon.com/images/I/91tDBrO2u9L._SL1000_.jpg',
      '2400': 'https://m.media-amazon.com/images/I/91tDBrO2u9L._SL2400_.jpg',
    },
    publication_name: 'Harry Potter',
    publisher_name: 'Pottermore Publishing',
    rating: {
      num_reviews: 5778,
      overall_distribution: {
        average_rating: 4.908237656063743,
        display_average_rating: '4.9',
        display_stars: 5,
        num_five_star_ratings: 148413,
        num_four_star_ratings: 8745,
        num_one_star_ratings: 536,
        num_ratings: 159390,
        num_three_star_ratings: 1351,
        num_two_star_ratings: 345,
      },
      performance_distribution: {
        average_rating: 4.847543752572637,
        display_average_rating: '4.8',
        display_stars: 5,
        num_five_star_ratings: 125438,
        num_four_star_ratings: 11288,
        num_one_star_ratings: 586,
        num_ratings: 140906,
        num_three_star_ratings: 2932,
        num_two_star_ratings: 662,
      },
      story_distribution: {
        average_rating: 4.924547369619677,
        display_average_rating: '4.9',
        display_stars: 5,
        num_five_star_ratings: 132148,
        num_four_star_ratings: 6860,
        num_one_star_ratings: 272,
        num_ratings: 140512,
        num_three_star_ratings: 1042,
        num_two_star_ratings: 190,
      },
    },
    release_date: '2015-11-20',
    runtime_length_min: 498,
    social_media_images: {
      facebook:
        'https://m.media-amazon.com/images/I/51U4p-ir2BL._SL10_UR1600,800_CR200,50,1200,630_CLa%7C1200,630%7C51U4p-ir2BL.jpg%7C0,0,1200,630+82,82,465,465_PJAdblSocialShare-Gradientoverlay-largeasin-0to70,TopLeft,0,0_PJAdblSocialShare-AudibleLogo-Large,TopLeft,600,270_OU01_ZBLISTENING%20ON,617,216,52,500,AudibleSansMd,30,255,255,255.jpg',
      twitter:
        'https://m.media-amazon.com/images/I/51U4p-ir2BL._SL10_UR1600,800_CR200,50,1024,512_CLa%7C1024,512%7C51U4p-ir2BL.jpg%7C0,0,1024,512+67,67,376,376_PJAdblSocialShare-Gradientoverlay-twitter-largeasin-0to60,TopLeft,0,0_PJAdblSocialShare-AudibleLogo-Medium,TopLeft,490,223_OU01_ZBLISTENING%20ON,483,152,55,450,AudibleSansMd,32,255,255,255.jpg',
    },
    thesaurus_subject_keywords: ['literature-and-fiction'],
    title: "Harry Potter and the Sorcerer's Stone, Book 1",
  },
  response_groups: [
    'always-returned',
    'contributors',
    'rating',
    'media',
    'product_attrs',
  ],
};

const searchResponse = {
  product_filters: [],
  products: [
    {
      asin: 'B017V4IM1G',
      authors: [{ asin: 'B000AP9A6K', name: 'J.K. Rowling' }],
      available_codecs: [
        {
          enhanced_codec: 'LC_32_22050_stereo',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'aax_22_32',
        },
        {
          enhanced_codec: 'LC_64_22050_stereo',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'aax_22_64',
        },
        {
          enhanced_codec: 'format4',
          format: 'Format4',
          is_kindle_enhanced: false,
          name: 'format4',
        },
        {
          enhanced_codec: 'mp42232',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'mp4_22_32',
        },
        {
          enhanced_codec: 'mp42264',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'mp4_22_64',
        },
        {
          enhanced_codec: 'aax',
          format: 'Enhanced',
          is_kindle_enhanced: false,
          name: 'aax',
        },
      ],
      content_delivery_type: 'SinglePartBook',
      content_type: 'Product',
      format_type: 'unabridged',
      has_children: false,
      is_adult_product: false,
      is_listenable: true,
      is_purchasability_suppressed: false,
      issue_date: '2015-11-20',
      language: 'english',
      merchandising_summary:
        '<p>Harry Potter is a wizard - and not only a wizard, he’s an incredibly famous wizard. Rubeus Hagrid spirits him away from his less-than-fortunate life to Hogwarts School of Witchcraft and Wizardry, setting into motion an incredible adventure....</p>',
      narrators: [{ name: 'Jim Dale' }],
      product_images: {
        '500': 'https://m.media-amazon.com/images/I/51U4p-ir2BL._SL500_.jpg',
        '1000': 'https://m.media-amazon.com/images/I/91tDBrO2u9L._SL1000_.jpg',
        '2400': 'https://m.media-amazon.com/images/I/91tDBrO2u9L._SL2400_.jpg',
      },
      publication_name: 'Harry Potter',
      publisher_name: 'Pottermore Publishing',
      rating: {
        num_reviews: 5778,
        overall_distribution: {
          average_rating: 4.908237656063743,
          display_average_rating: '4.9',
          display_stars: 5,
          num_five_star_ratings: 148413,
          num_four_star_ratings: 8745,
          num_one_star_ratings: 536,
          num_ratings: 159390,
          num_three_star_ratings: 1351,
          num_two_star_ratings: 345,
        },
        performance_distribution: {
          average_rating: 4.847543752572637,
          display_average_rating: '4.8',
          display_stars: 5,
          num_five_star_ratings: 125438,
          num_four_star_ratings: 11288,
          num_one_star_ratings: 586,
          num_ratings: 140906,
          num_three_star_ratings: 2932,
          num_two_star_ratings: 662,
        },
        story_distribution: {
          average_rating: 4.924547369619677,
          display_average_rating: '4.9',
          display_stars: 5,
          num_five_star_ratings: 132148,
          num_four_star_ratings: 6860,
          num_one_star_ratings: 272,
          num_ratings: 140512,
          num_three_star_ratings: 1042,
          num_two_star_ratings: 190,
        },
      },
      release_date: '2015-11-20',
      runtime_length_min: 498,
      social_media_images: {
        facebook:
          'https://m.media-amazon.com/images/I/51U4p-ir2BL._SL10_UR1600,800_CR200,50,1200,630_CLa%7C1200,630%7C51U4p-ir2BL.jpg%7C0,0,1200,630+82,82,465,465_PJAdblSocialShare-Gradientoverlay-largeasin-0to70,TopLeft,0,0_PJAdblSocialShare-AudibleLogo-Large,TopLeft,600,270_OU01_ZBLISTENING%20ON,617,216,52,500,AudibleSansMd,30,255,255,255.jpg',
        twitter:
          'https://m.media-amazon.com/images/I/51U4p-ir2BL._SL10_UR1600,800_CR200,50,1024,512_CLa%7C1024,512%7C51U4p-ir2BL.jpg%7C0,0,1024,512+67,67,376,376_PJAdblSocialShare-Gradientoverlay-twitter-largeasin-0to60,TopLeft,0,0_PJAdblSocialShare-AudibleLogo-Medium,TopLeft,490,223_OU01_ZBLISTENING%20ON,483,152,55,450,AudibleSansMd,32,255,255,255.jpg',
      },
      thesaurus_subject_keywords: ['literature-and-fiction'],
      title: "Harry Potter and the Sorcerer's Stone, Book 1",
    },
    {
      asin: 'B017V4NUPO',
      authors: [{ asin: 'B000AP9A6K', name: 'J.K. Rowling' }],
      available_codecs: [
        {
          enhanced_codec: 'format4',
          format: 'Format4',
          is_kindle_enhanced: false,
          name: 'format4',
        },
        {
          enhanced_codec: 'LC_32_22050_stereo',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'aax_22_32',
        },
        {
          enhanced_codec: 'LC_64_22050_stereo',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'aax_22_64',
        },
        {
          enhanced_codec: 'mp42264',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'mp4_22_64',
        },
        {
          enhanced_codec: 'piff2264',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'piff_22_64',
        },
        {
          enhanced_codec: 'piff2232',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'piff_22_32',
        },
        {
          enhanced_codec: 'mp42232',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'mp4_22_32',
        },
        {
          enhanced_codec: 'aax',
          format: 'Enhanced',
          is_kindle_enhanced: false,
          name: 'aax',
        },
      ],
      content_delivery_type: 'MultiPartBook',
      content_type: 'Product',
      format_type: 'unabridged',
      has_children: true,
      is_adult_product: false,
      is_listenable: true,
      is_purchasability_suppressed: false,
      issue_date: '2015-11-20',
      language: 'english',
      merchandising_summary:
        "The Triwizard Tournament is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter - but that doesn't stop Harry dreaming that he will win the competition....",
      narrators: [{ name: 'Jim Dale' }],
      product_images: {
        '500': 'https://m.media-amazon.com/images/I/51g0LdfhtvL._SL500_.jpg',
        '1000': 'https://m.media-amazon.com/images/I/91wE69EbTKL._SL1000_.jpg',
        '2400': 'https://m.media-amazon.com/images/I/91wE69EbTKL._SL2400_.jpg',
      },
      publication_name: 'Harry Potter',
      publisher_name: 'Pottermore Publishing',
      rating: {
        num_reviews: 1854,
        overall_distribution: {
          average_rating: 4.938040345821325,
          display_average_rating: '4.9',
          display_stars: 5,
          num_five_star_ratings: 92447,
          num_four_star_ratings: 3910,
          num_one_star_ratings: 192,
          num_ratings: 97160,
          num_three_star_ratings: 491,
          num_two_star_ratings: 120,
        },
        performance_distribution: {
          average_rating: 4.90875645563744,
          display_average_rating: '4.9',
          display_stars: 5,
          num_five_star_ratings: 80245,
          num_four_star_ratings: 4558,
          num_one_star_ratings: 193,
          num_ratings: 86165,
          num_three_star_ratings: 975,
          num_two_star_ratings: 194,
        },
        story_distribution: {
          average_rating: 4.943173878615679,
          display_average_rating: '4.9',
          display_stars: 5,
          num_five_star_ratings: 81901,
          num_four_star_ratings: 3327,
          num_one_star_ratings: 97,
          num_ratings: 85876,
          num_three_star_ratings: 488,
          num_two_star_ratings: 63,
        },
      },
      release_date: '2015-11-20',
      runtime_length_min: 1237,
      social_media_images: {
        facebook:
          'https://m.media-amazon.com/images/I/51g0LdfhtvL._SL10_UR1600,800_CR200,50,1200,630_CLa%7C1200,630%7C51g0LdfhtvL.jpg%7C0,0,1200,630+82,82,465,465_PJAdblSocialShare-Gradientoverlay-largeasin-0to70,TopLeft,0,0_PJAdblSocialShare-AudibleLogo-Large,TopLeft,600,270_OU01_ZBLISTENING%20ON,617,216,52,500,AudibleSansMd,30,255,255,255.jpg',
        twitter:
          'https://m.media-amazon.com/images/I/51g0LdfhtvL._SL10_UR1600,800_CR200,50,1024,512_CLa%7C1024,512%7C51g0LdfhtvL.jpg%7C0,0,1024,512+67,67,376,376_PJAdblSocialShare-Gradientoverlay-twitter-largeasin-0to60,TopLeft,0,0_PJAdblSocialShare-AudibleLogo-Medium,TopLeft,490,223_OU01_ZBLISTENING%20ON,483,152,55,450,AudibleSansMd,32,255,255,255.jpg',
      },
      thesaurus_subject_keywords: ['literature-and-fiction'],
      title: 'Harry Potter and the Goblet of Fire, Book 4',
    },
    {
      asin: 'B017V4JA2Q',
      authors: [{ asin: 'B000AP9A6K', name: 'J.K. Rowling' }],
      available_codecs: [
        {
          enhanced_codec: 'format4',
          format: 'Format4',
          is_kindle_enhanced: false,
          name: 'format4',
        },
        {
          enhanced_codec: 'LC_64_22050_stereo',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'aax_22_64',
        },
        {
          enhanced_codec: 'LC_32_22050_stereo',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'aax_22_32',
        },
        {
          enhanced_codec: 'mp42232',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'mp4_22_32',
        },
        {
          enhanced_codec: 'mp42264',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'mp4_22_64',
        },
        {
          enhanced_codec: 'piff2264',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'piff_22_64',
        },
        {
          enhanced_codec: 'piff2232',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'piff_22_32',
        },
        {
          enhanced_codec: 'aax',
          format: 'Enhanced',
          is_kindle_enhanced: false,
          name: 'aax',
        },
      ],
      content_delivery_type: 'MultiPartBook',
      content_type: 'Product',
      format_type: 'unabridged',
      has_children: true,
      is_adult_product: false,
      is_listenable: true,
      is_purchasability_suppressed: false,
      issue_date: '2015-11-20',
      language: 'english',
      merchandising_summary:
        "<p>When the Knight Bus crashes through the darkness and screeches to a halt in front of him, it's the start of another far-from-ordinary year at Hogwarts for Harry Potter....</p>",
      narrators: [{ name: 'Jim Dale' }],
      product_images: {
        '500': 'https://m.media-amazon.com/images/I/511LCj4HF2L._SL500_.jpg',
        '1000': 'https://m.media-amazon.com/images/I/91wkoe9lV4L._SL1000_.jpg',
        '2400': 'https://m.media-amazon.com/images/I/91wkoe9lV4L._SL2400_.jpg',
      },
      publication_name: 'Harry Potter',
      publisher_name: 'Pottermore Publishing',
      rating: {
        num_reviews: 1996,
        overall_distribution: {
          average_rating: 4.938644597992437,
          display_average_rating: '4.9',
          display_stars: 5,
          num_five_star_ratings: 96151,
          num_four_star_ratings: 4046,
          num_one_star_ratings: 193,
          num_ratings: 101018,
          num_three_star_ratings: 504,
          num_two_star_ratings: 124,
        },
        performance_distribution: {
          average_rating: 4.902909476740939,
          display_average_rating: '4.9',
          display_stars: 5,
          num_five_star_ratings: 83036,
          num_four_star_ratings: 4955,
          num_one_star_ratings: 211,
          num_ratings: 89535,
          num_three_star_ratings: 1105,
          num_two_star_ratings: 228,
        },
        story_distribution: {
          average_rating: 4.9455240272547965,
          display_average_rating: '4.9',
          display_stars: 5,
          num_five_star_ratings: 85272,
          num_four_star_ratings: 3330,
          num_one_star_ratings: 95,
          num_ratings: 89232,
          num_three_star_ratings: 454,
          num_two_star_ratings: 81,
        },
      },
      release_date: '2015-11-20',
      runtime_length_min: 709,
      social_media_images: {
        facebook:
          'https://m.media-amazon.com/images/I/511LCj4HF2L._SL10_UR1600,800_CR200,50,1200,630_CLa%7C1200,630%7C511LCj4HF2L.jpg%7C0,0,1200,630+82,82,465,465_PJAdblSocialShare-Gradientoverlay-largeasin-0to70,TopLeft,0,0_PJAdblSocialShare-AudibleLogo-Large,TopLeft,600,270_OU01_ZBLISTENING%20ON,617,216,52,500,AudibleSansMd,30,255,255,255.jpg',
        twitter:
          'https://m.media-amazon.com/images/I/511LCj4HF2L._SL10_UR1600,800_CR200,50,1024,512_CLa%7C1024,512%7C511LCj4HF2L.jpg%7C0,0,1024,512+67,67,376,376_PJAdblSocialShare-Gradientoverlay-twitter-largeasin-0to60,TopLeft,0,0_PJAdblSocialShare-AudibleLogo-Medium,TopLeft,490,223_OU01_ZBLISTENING%20ON,483,152,55,450,AudibleSansMd,32,255,255,255.jpg',
      },
      thesaurus_subject_keywords: ['literature-and-fiction'],
      title: 'Harry Potter and the Prisoner of Azkaban, Book 3',
    },
    {
      asin: 'B017V4NMX4',
      authors: [{ asin: 'B000AP9A6K', name: 'J.K. Rowling' }],
      available_codecs: [
        {
          enhanced_codec: 'LC_64_22050_stereo',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'aax_22_64',
        },
        {
          enhanced_codec: 'LC_32_22050_stereo',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'aax_22_32',
        },
        {
          enhanced_codec: 'format4',
          format: 'Format4',
          is_kindle_enhanced: false,
          name: 'format4',
        },
        {
          enhanced_codec: 'piff2264',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'piff_22_64',
        },
        {
          enhanced_codec: 'mp42232',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'mp4_22_32',
        },
        {
          enhanced_codec: 'mp42264',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'mp4_22_64',
        },
        {
          enhanced_codec: 'piff2232',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'piff_22_32',
        },
        {
          enhanced_codec: 'aax',
          format: 'Enhanced',
          is_kindle_enhanced: false,
          name: 'aax',
        },
      ],
      content_delivery_type: 'MultiPartBook',
      content_type: 'Product',
      format_type: 'unabridged',
      has_children: true,
      is_adult_product: false,
      is_listenable: true,
      is_purchasability_suppressed: false,
      issue_date: '2015-11-20',
      language: 'english',
      merchandising_summary:
        "Dark times have come to Hogwarts. After the Dementors' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him....",
      narrators: [{ name: 'Jim Dale' }],
      product_images: {
        '500': 'https://m.media-amazon.com/images/I/51ok3DFBrRL._SL500_.jpg',
        '1000': 'https://m.media-amazon.com/images/I/91lexie8rNL._SL1000_.jpg',
        '2400': 'https://m.media-amazon.com/images/I/91lexie8rNL._SL2400_.jpg',
      },
      publication_name: 'Harry Potter',
      publisher_name: 'Pottermore Publishing',
      rating: {
        num_reviews: 1760,
        overall_distribution: {
          average_rating: 4.9278290864582175,
          display_average_rating: '4.9',
          display_stars: 5,
          num_five_star_ratings: 84814,
          num_four_star_ratings: 4133,
          num_one_star_ratings: 187,
          num_ratings: 89870,
          num_three_star_ratings: 603,
          num_two_star_ratings: 133,
        },
        performance_distribution: {
          average_rating: 4.915908236179015,
          display_average_rating: '4.9',
          display_stars: 5,
          num_five_star_ratings: 74734,
          num_four_star_ratings: 3889,
          num_one_star_ratings: 177,
          num_ratings: 79770,
          num_three_star_ratings: 799,
          num_two_star_ratings: 171,
        },
        story_distribution: {
          average_rating: 4.920705067673906,
          display_average_rating: '4.9',
          display_stars: 5,
          num_five_star_ratings: 74479,
          num_four_star_ratings: 3963,
          num_one_star_ratings: 115,
          num_ratings: 79425,
          num_three_star_ratings: 729,
          num_two_star_ratings: 139,
        },
      },
      release_date: '2015-11-20',
      runtime_length_min: 1589,
      social_media_images: {
        facebook:
          'https://m.media-amazon.com/images/I/51ok3DFBrRL._SL10_UR1600,800_CR200,50,1200,630_CLa%7C1200,630%7C51ok3DFBrRL.jpg%7C0,0,1200,630+82,82,465,465_PJAdblSocialShare-Gradientoverlay-largeasin-0to70,TopLeft,0,0_PJAdblSocialShare-AudibleLogo-Large,TopLeft,600,270_OU01_ZBLISTENING%20ON,617,216,52,500,AudibleSansMd,30,255,255,255.jpg',
        twitter:
          'https://m.media-amazon.com/images/I/51ok3DFBrRL._SL10_UR1600,800_CR200,50,1024,512_CLa%7C1024,512%7C51ok3DFBrRL.jpg%7C0,0,1024,512+67,67,376,376_PJAdblSocialShare-Gradientoverlay-twitter-largeasin-0to60,TopLeft,0,0_PJAdblSocialShare-AudibleLogo-Medium,TopLeft,490,223_OU01_ZBLISTENING%20ON,483,152,55,450,AudibleSansMd,32,255,255,255.jpg',
      },
      thesaurus_subject_keywords: ['literature-and-fiction'],
      title: 'Harry Potter and the Order of the Phoenix, Book 5',
    },
    {
      asin: 'B017V4IWVG',
      authors: [{ asin: 'B000AP9A6K', name: 'J.K. Rowling' }],
      available_codecs: [
        {
          enhanced_codec: 'LC_32_22050_stereo',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'aax_22_32',
        },
        {
          enhanced_codec: 'LC_64_22050_stereo',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'aax_22_64',
        },
        {
          enhanced_codec: 'format4',
          format: 'Format4',
          is_kindle_enhanced: false,
          name: 'format4',
        },
        {
          enhanced_codec: 'mp42264',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'mp4_22_64',
        },
        {
          enhanced_codec: 'mp42232',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'mp4_22_32',
        },
        {
          enhanced_codec: 'piff2264',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'piff_22_64',
        },
        {
          enhanced_codec: 'piff2232',
          format: 'Enhanced',
          is_kindle_enhanced: true,
          name: 'piff_22_32',
        },
        {
          enhanced_codec: 'aax',
          format: 'Enhanced',
          is_kindle_enhanced: false,
          name: 'aax',
        },
      ],
      content_delivery_type: 'SinglePartBook',
      content_type: 'Product',
      format_type: 'unabridged',
      has_children: false,
      is_adult_product: false,
      is_listenable: true,
      is_purchasability_suppressed: false,
      issue_date: '2015-11-20',
      language: 'english',
      merchandising_summary:
        'Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start....',
      narrators: [{ name: 'Jim Dale' }],
      product_images: {
        '500': 'https://m.media-amazon.com/images/I/51RDEwuovQL._SL500_.jpg',
        '1000': 'https://m.media-amazon.com/images/I/91esnMgE8dL._SL1000_.jpg',
        '2400': 'https://m.media-amazon.com/images/I/91esnMgE8dL._SL2400_.jpg',
      },
      publication_name: 'Harry Potter',
      publisher_name: 'Pottermore Publishing',
      rating: {
        num_reviews: 2207,
        overall_distribution: {
          average_rating: 4.917948809961692,
          display_average_rating: '4.9',
          display_stars: 5,
          num_five_star_ratings: 104282,
          num_four_star_ratings: 5929,
          num_one_star_ratings: 269,
          num_ratings: 111467,
          num_three_star_ratings: 820,
          num_two_star_ratings: 167,
        },
        performance_distribution: {
          average_rating: 4.886912312391545,
          display_average_rating: '4.9',
          display_stars: 5,
          num_five_star_ratings: 90248,
          num_four_star_ratings: 6293,
          num_one_star_ratings: 272,
          num_ratings: 98543,
          num_three_star_ratings: 1427,
          num_two_star_ratings: 303,
        },
        story_distribution: {
          average_rating: 4.921261927310868,
          display_average_rating: '4.9',
          display_stars: 5,
          num_five_star_ratings: 91941,
          num_four_star_ratings: 5182,
          num_one_star_ratings: 143,
          num_ratings: 98199,
          num_three_star_ratings: 821,
          num_two_star_ratings: 112,
        },
      },
      release_date: '2015-11-20',
      runtime_length_min: 543,
      social_media_images: {
        facebook:
          'https://m.media-amazon.com/images/I/51RDEwuovQL._SL10_UR1600,800_CR200,50,1200,630_CLa%7C1200,630%7C51RDEwuovQL.jpg%7C0,0,1200,630+82,82,465,465_PJAdblSocialShare-Gradientoverlay-largeasin-0to70,TopLeft,0,0_PJAdblSocialShare-AudibleLogo-Large,TopLeft,600,270_OU01_ZBLISTENING%20ON,617,216,52,500,AudibleSansMd,30,255,255,255.jpg',
        twitter:
          'https://m.media-amazon.com/images/I/51RDEwuovQL._SL10_UR1600,800_CR200,50,1024,512_CLa%7C1024,512%7C51RDEwuovQL.jpg%7C0,0,1024,512+67,67,376,376_PJAdblSocialShare-Gradientoverlay-twitter-largeasin-0to60,TopLeft,0,0_PJAdblSocialShare-AudibleLogo-Medium,TopLeft,490,223_OU01_ZBLISTENING%20ON,483,152,55,450,AudibleSansMd,32,255,255,255.jpg',
      },
      thesaurus_subject_keywords: ['literature-and-fiction'],
      title: 'Harry Potter and the Chamber of Secrets, Book 2',
    },
  ],
  response_groups: [
    'always-returned',
    'contributors',
    'rating',
    'media',
    'product_attrs',
  ],
  total_results: 213,
} as unknown;
